services:
  - type: web
    name: "RESTful with more FastAPI"
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: poetry install
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT